"""
features/multilang_codegen.py
================================
Multi-language code generation bridge for the Crucible pipeline.

Takes the Python code generated by Stage 4 and uses the LLM to produce
equivalent implementations in TypeScript, Go, or Rust.  Each language
translation runs as an independent LLM task, preserving the original Python
as the authoritative reference.

Design principles
-----------------
* **Additive**: never modifies Stage 4 output; translations live in a
  separate ``code_<lang>/`` subdirectory within the run directory.
* **Best-effort**: if a file cannot be translated the error is logged and
  the next file is attempted — one failure never blocks the entire batch.
* **Scope-aware**: TypeScript and Go targets are fully supported; Rust is
  available as an experimental option (``MULTILANG_ENABLE_RUST=1``).
* **Token-efficient**: each file is translated independently so context
  windows are not exhausted on large codebases.

Supported language targets
--------------------------
* ``typescript`` — TypeScript 5.x, ESM, strict mode, no any
* ``go``         — Go 1.21+, idiomatic packages, error returns
* ``rust``       — Rust 2021 edition (opt-in via ``MULTILANG_ENABLE_RUST=1``)
* ``julia``      — Julia 1.9+, scientific computing focus (opt-in via ``MULTILANG_ENABLE_JULIA=1``)

Environment variables
---------------------
``MULTILANG_MAX_FILES``     — max files to translate (default 10)
``MULTILANG_MAX_CHARS``     — max chars per file sent to LLM (default 4 000)
``MULTILANG_ENABLE_RUST``   — set to ``1`` to enable Rust target (default off)
``MULTILANG_ENABLE_JULIA``  — set to ``1`` to enable Julia target (default off)

Usage::

    from crucible.features.multilang_codegen import (
        translate_run_to_languages,
        MultiLangConfig,
    )

    config = MultiLangConfig(
        languages=["typescript", "go"],
    )
    result = translate_run_to_languages(
        run_dir="/path/to/saved_projects/my_run",
        config=config,
        llm=my_llm,
    )
    for lang, files in result.files_written.items():
        print(f"{lang}: {len(files)} file(s) written")
"""
from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set

# ── Configuration ─────────────────────────────────────────────────────────────

try:
    from .. import _env
except ImportError:  # pragma: no cover - script-mode fallback
    import _env  # type: ignore[no-redef]


def _env_int(name: str, default: int) -> int:
    return _env.env_int(name, default)

def _env_bool(name: str, default: bool) -> bool:
    return _env.env_bool(name, default)


_MAX_FILES: int = max(1, _env_int("MULTILANG_MAX_FILES", 10))
_MAX_CHARS: int = max(1, _env_int("MULTILANG_MAX_CHARS", 4_000))
_RUST_ENABLED: bool = _env_bool("MULTILANG_ENABLE_RUST", False)
_JULIA_ENABLED: bool = _env_bool("MULTILANG_ENABLE_JULIA", False)

_SUPPORTED_TARGETS: Set[str] = {"typescript", "go", "lean"}
if _RUST_ENABLED:
    _SUPPORTED_TARGETS.add("rust")
if _JULIA_ENABLED:
    _SUPPORTED_TARGETS.add("julia")

# ── Language-specific prompt templates ────────────────────────────────────────

_LANG_PROMPTS: Dict[str, str] = {
    "typescript": """\
You are an expert TypeScript developer. Translate the following Python module \
to idiomatic TypeScript 5.x with strict mode.

Rules:
- Use ESM import/export syntax (no CommonJS require).
- Use TypeScript interfaces and types instead of Python dataclasses.
- Replace Python `Optional[X]` with `X | null`.
- Replace Python exceptions with typed `Result<T, E>` or throw Error objects.
- Use `async/await` for any I/O-bound operations.
- Do NOT use `any` unless absolutely unavoidable — use `unknown` or proper types.
- Add a brief JSDoc comment for every exported function/class.
- Output ONLY the TypeScript code, no markdown fences, no explanations.

Python source:
```python
{source}
```
""",
    "go": """\
You are an expert Go developer. Translate the following Python module to \
idiomatic Go 1.21+.

Rules:
- Use a single package named after the file (snake_case → camelCase for exports).
- Return `(T, error)` pairs; never panic on expected errors.
- Use `struct` types to replace Python dataclasses.
- Use `context.Context` as the first parameter for any network/IO operations.
- Follow gofmt style — use tabs for indentation.
- Add a godoc comment for every exported type and function.
- Output ONLY the Go code, no markdown fences, no explanations.

Python source:
```python
{source}
```
""",
    "rust": """\
You are an expert Rust developer. Translate the following Python module to \
idiomatic Rust 2021 edition.

Rules:
- Use `Result<T, Box<dyn std::error::Error>>` for fallible functions.
- Represent Python dataclasses as `#[derive(Debug, Clone)] struct`.
- Use `Option<T>` instead of Python `Optional[T]`.
- Prefer `impl Display` and `impl Error` for custom error types.
- Avoid `unwrap()` and `expect()` in library code; propagate with `?`.
- Add doc comments (`///`) for every public item.
- Output ONLY the Rust code, no markdown fences, no explanations.

Python source:
```python
{source}
```
""",
    "julia": """\
You are an expert Julia developer specializing in scientific computing and quantitative finance. \
Translate the following Python module to idiomatic Julia 1.9+.

Rules:
- Use Julia's type system: annotate function arguments and return types where helpful.
- Replace Python dataclasses with Julia `struct` definitions (use `mutable struct` for mutable state).
- Replace Python `Optional[X]` with `Union{X, Nothing}`.
- Use `try/catch` blocks with typed exception handling.
- Replace pandas DataFrames with DataFrames.jl conventions (import as needed).
- Use `@kwdef` for structs with keyword argument constructors.
- Prefer Julia's built-in `Statistics`, `LinearAlgebra`, and `Random` modules over Python equivalents.
- For numerical computation, use BLAS/LAPACK via Julia's standard library where applicable.
- Add docstrings using Julia's triple-quoted string convention before each function.
- Output ONLY the Julia code, no markdown fences, no explanations.

Python source:
```python
{source}
```
""",
    "lean": """\
You are an expert QuantConnect/Lean algorithmic trading developer. \
Translate the following Python trading strategy into a complete QuantConnect Lean \
Algorithm class in Python (LEAN uses Python 3.x).

Rules:
- The output must be a class that extends `QCAlgorithm`.
- Implement `Initialize(self)` to set start/end dates, cash, resolution, and add securities.
- Implement `OnData(self, data: Slice)` for bar-by-bar logic.
- Replace pandas/numpy with LEAN's built-in `RollingWindow`, `SimpleMovingAverage`, \
`BollingerBands`, `RelativeStrengthIndex`, `AverageTrueRange`, etc. where applicable.
- Use `self.SetHoldings(symbol, weight)` or `self.MarketOrder(symbol, quantity)` for orders.
- Use `self.Portfolio[symbol].IsLong/IsShort/Invested` for position checks.
- Add `self.SetBrokerageModel(BrokerageName.InteractiveBrokersBrokerage)` in Initialize.
- Add `self.SetWarmUp(timedelta(days=30))` if indicators need warm-up.
- Do NOT import pandas, numpy, or other external libraries (use LEAN's built-ins only).
- Output ONLY the Python code, no markdown fences, no explanations.

Original Python strategy:
```python
{source}
```
""",
}

_LANG_EXTENSIONS: Dict[str, str] = {
    "typescript": ".ts",
    "go": ".go",
    "rust": ".rs",
    "julia": ".jl",
    "lean": "_lean.py",
}

_LANG_DISPLAY: Dict[str, str] = {
    "typescript": "TypeScript",
    "go": "Go",
    "rust": "Rust",
    "julia": "Julia",
    "lean": "QuantConnect/Lean",
}

# ── Lean scaffold template ────────────────────────────────────────────────────

_LEAN_SCAFFOLD_TEMPLATE = '''\
# QuantConnect / Lean Engine scaffold
# Generated by Crucible — review and adapt before live deployment
from AlgorithmImports import *
from datetime import timedelta


class {class_name}(QCAlgorithm):
    """
    {strategy_description}
    Auto-scaffolded from Crucible pipeline output.
    """

    def Initialize(self) -> None:
        self.SetStartDate(2020, 1, 1)
        self.SetEndDate(2024, 1, 1)
        self.SetCash(100_000)
        self.SetBrokerageModel(
            BrokerageName.InteractiveBrokersBrokerage,
            AccountType.Margin,
        )

        self.symbol = self.AddEquity("{symbol}", Resolution.Daily).Symbol
        self.SetBenchmark(self.symbol)

        # ── Indicators ────────────────────────────────────────────────────────
{indicators}

        self.SetWarmUp(timedelta(days=50))

    def OnData(self, data: Slice) -> None:
        if self.IsWarmingUp:
            return
        if not data.ContainsKey(self.symbol):
            return

        # ── Trading logic (adapt from original strategy) ──────────────────────
{trading_logic}

    def OnOrderEvent(self, orderEvent: OrderEvent) -> None:
        if orderEvent.Status == OrderStatus.Filled:
            self.Log(f"Order filled: {{orderEvent}}")
'''

# ── Data models ───────────────────────────────────────────────────────────────

@dataclass
class MultiLangConfig:
    """Configuration for a multi-language translation job."""

    languages: List[str] = field(default_factory=lambda: ["typescript", "go"])
    max_files: int = 0                # 0 → use env default
    max_chars_per_file: int = 0       # 0 → use env default
    # Specific file names to translate (empty = all .py files)
    include_files: List[str] = field(default_factory=list)
    # File names to skip (useful for __init__.py, conftest.py, etc.)
    exclude_files: List[str] = field(default_factory=lambda: [
        "__init__.py", "conftest.py", "setup.py",
    ])


@dataclass
class TranslationResult:
    """Result of translating one Python file to one target language."""

    source_path: str
    target_language: str
    target_path: str
    success: bool
    char_count: int = 0
    error: Optional[str] = None


@dataclass
class MultiLangResult:
    """Aggregated result of a multi-language translation job."""

    run_dir: str
    files_written: Dict[str, List[str]] = field(default_factory=dict)
    translations: List[TranslationResult] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    manifest_path: Optional[str] = None

    @property
    def total_files(self) -> int:
        return sum(len(v) for v in self.files_written.values())

    @property
    def total_errors(self) -> int:
        return len(self.errors)

    def summary_text(self) -> str:
        lines = ["Multi-Language CodeGen Summary"]
        for lang, paths in sorted(self.files_written.items()):
            lines.append(f"  {_LANG_DISPLAY.get(lang, lang)}: {len(paths)} file(s)")
        if self.errors:
            lines.append(f"  Errors: {len(self.errors)}")
            for e in self.errors[:3]:
                lines.append(f"    - {e}")
        return "\n".join(lines)


# ── LLM adapter ───────────────────────────────────────────────────────────────

def _invoke_llm_translation(llm: Any, prompt: str) -> str:
    """
    Invoke the LLM for a translation task and return the generated code.
    Strips markdown fences if the model wraps the output anyway.
    """
    try:
        from langchain_core.messages import HumanMessage
        _has_lc = True
    except ImportError:
        _has_lc = False

    if _has_lc:
        result = llm.invoke([HumanMessage(content=prompt)])
    else:
        result = llm.invoke([{"role": "user", "content": prompt}])
    text = str(result.content) if hasattr(result, "content") else str(result)

    # Strip markdown code fences that some models emit despite instructions
    return _strip_code_fences(text)


def _strip_code_fences(text: str) -> str:
    """Remove leading/trailing markdown code fences."""
    lines = text.strip().splitlines()
    if not lines:
        return text
    start = 0
    end = len(lines)
    if lines[0].startswith("```"):
        start = 1
    if end > start and lines[end - 1].strip() == "```":
        end -= 1
    return "\n".join(lines[start:end])


# ── File helpers ──────────────────────────────────────────────────────────────

def _collect_python_files(
    run_dir: str,
    config: MultiLangConfig,
    max_files: int,
    max_chars: int,
) -> List[tuple]:
    """
    Return list of ``(rel_path, content)`` tuples for Python files in
    ``{run_dir}/code/``.
    """
    code_dir = os.path.join(run_dir, "code")
    if not os.path.isdir(code_dir):
        return []

    include_set = set(config.include_files)
    exclude_set = set(config.exclude_files)
    results: List[tuple] = []

    for dirpath, _dirs, filenames in os.walk(code_dir):
        for fname in sorted(filenames):
            if not fname.endswith(".py"):
                continue
            if fname in exclude_set:
                continue
            if include_set and fname not in include_set:
                continue
            if len(results) >= max_files:
                break
            fpath = os.path.join(dirpath, fname)
            try:
                with open(fpath, "r", encoding="utf-8", errors="replace") as fh:
                    content = fh.read(max_chars)
                rel = os.path.relpath(fpath, code_dir)
                results.append((rel, content))
            except OSError:
                pass
        if len(results) >= max_files:
            break

    return results


def _output_dir_for_lang(run_dir: str, lang: str) -> str:
    return os.path.join(run_dir, f"code_{lang}")


def _target_filename(python_rel_path: str, lang: str) -> str:
    """Convert ``path/to/module.py`` → ``path/to/module.ts`` (etc.)."""
    base, _ = os.path.splitext(python_rel_path)
    return base + _LANG_EXTENSIONS[lang]


# ── Translation core ──────────────────────────────────────────────────────────

def _translate_file(
    rel_path: str,
    source: str,
    lang: str,
    run_dir: str,
    llm: Any,
) -> TranslationResult:
    """Translate one Python file to *lang* and write the output."""
    prompt_template = _LANG_PROMPTS.get(lang)
    if not prompt_template:
        return TranslationResult(
            source_path=rel_path,
            target_language=lang,
            target_path="",
            success=False,
            error=f"No prompt template for language: {lang}",
        )

    prompt = prompt_template.format(source=source)

    try:
        translated = _invoke_llm_translation(llm, prompt)
    except Exception as exc:
        return TranslationResult(
            source_path=rel_path,
            target_language=lang,
            target_path="",
            success=False,
            error=f"LLM error: {exc}",
        )

    if not translated.strip():
        return TranslationResult(
            source_path=rel_path,
            target_language=lang,
            target_path="",
            success=False,
            error="LLM returned empty translation",
        )

    target_rel = _target_filename(rel_path, lang)
    out_dir = _output_dir_for_lang(run_dir, lang)
    out_path = os.path.join(out_dir, target_rel)

    try:
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        _tmp_out = out_path + ".tmp"
        try:
            with open(_tmp_out, "w", encoding="utf-8") as fh:
                fh.write(translated)
            os.replace(_tmp_out, out_path)
        except OSError:
            try:
                os.unlink(_tmp_out)
            except OSError:
                pass
            raise
        return TranslationResult(
            source_path=rel_path,
            target_language=lang,
            target_path=out_path,
            success=True,
            char_count=len(translated),
        )
    except OSError as exc:
        return TranslationResult(
            source_path=rel_path,
            target_language=lang,
            target_path="",
            success=False,
            error=f"Write error: {exc}",
        )


# ── Lean scaffold generator ───────────────────────────────────────────────────

def _to_pascal_case(text: str) -> str:
    """Convert snake_case or space-separated text to PascalCase class name."""
    parts = re.split(r"[\s_\-]+", text.strip())
    return "".join(p.capitalize() for p in parts if p) or "QuantStrategy"


def _extract_strategy_name(code_dir: str) -> str:
    """
    Attempt to extract a strategy name from strategy.py or config.py.
    Falls back to the directory name.
    """
    for candidate in ("strategy.py", "config.py", "main.py"):
        fpath = os.path.join(code_dir, candidate)
        if not os.path.isfile(fpath):
            continue
        try:
            with open(fpath, "r", encoding="utf-8", errors="replace") as fh:
                source = fh.read(4096)
            # Look for STRATEGY_NAME = "..." or strategy_name = "..."
            m = re.search(
                r'(?:STRATEGY_NAME|strategy_name|ALGO_NAME|algo_name)\s*=\s*["\']([^"\']+)["\']',
                source,
                re.IGNORECASE,
            )
            if m:
                return m.group(1)
            # Look for class definition
            m2 = re.search(r"^class\s+(\w+)", source, re.MULTILINE)
            if m2:
                return m2.group(1)
        except OSError:
            pass
    return os.path.basename(os.path.dirname(code_dir))


def _extract_primary_symbol(code_dir: str) -> str:
    """Attempt to detect the primary trading symbol from the code."""
    for candidate in ("strategy.py", "config.py", "main.py", "data_loader.py"):
        fpath = os.path.join(code_dir, candidate)
        if not os.path.isfile(fpath):
            continue
        try:
            with open(fpath, "r", encoding="utf-8", errors="replace") as fh:
                source = fh.read(4096)
            # Common patterns: SYMBOL = "AAPL", symbol = "BTC-USD"
            m = re.search(
                r'(?:SYMBOL|symbol|TICKER|ticker)\s*=\s*["\']([A-Z0-9\-\.]+)["\']',
                source,
                re.IGNORECASE,
            )
            if m:
                return m.group(1).upper()
        except OSError:
            pass
    return "SPY"


def generate_lean_scaffold(run_dir: str) -> str:
    """
    Generate a minimal but complete QuantConnect/Lean ``QCAlgorithm`` subclass
    scaffold WITHOUT using an LLM.

    Reads strategy name and symbol from ``{run_dir}/code/strategy.py`` or
    ``{run_dir}/code/config.py`` when available.

    Saves the scaffold to ``{run_dir}/code_lean/algorithm.py`` and returns
    the absolute path to the written file.

    The scaffold is functional as a skeleton: it compiles in Lean, sets up
    a daily resolution SPY (or detected symbol) strategy, and includes
    placeholder indicators/logic sections for the developer to fill in.
    """
    code_dir = os.path.join(run_dir, "code")

    strategy_raw = _extract_strategy_name(code_dir)
    class_name = _to_pascal_case(strategy_raw) + "Algorithm"
    symbol = _extract_primary_symbol(code_dir)

    # Build placeholder indicator section (common indicators as comments)
    indicators_lines = [
        "        self.sma_fast = self.SMA(self.symbol, 20, Resolution.Daily)",
        "        self.sma_slow = self.SMA(self.symbol, 50, Resolution.Daily)",
        "        self.rsi = self.RSI(self.symbol, 14, MovingAverageType.Wilders, Resolution.Daily)",
        "        self.bb = self.BB(self.symbol, 20, 2, MovingAverageType.Simple, Resolution.Daily)",
        "        self.atr = self.ATR(self.symbol, 14, MovingAverageType.Simple, Resolution.Daily)",
    ]

    trading_lines = [
        "        price = self.Securities[self.symbol].Price",
        "        if not self.sma_fast.IsReady or not self.sma_slow.IsReady:",
        "            return",
        "",
        "        # ── Example: SMA crossover logic ─────────────────────────────",
        "        is_uptrend = self.sma_fast.Current.Value > self.sma_slow.Current.Value",
        "        is_invested = self.Portfolio[self.symbol].Invested",
        "",
        "        if is_uptrend and not is_invested:",
        "            self.SetHoldings(self.symbol, 1.0)",
        "            self.Log(f'BUY  {self.symbol}  price={price:.2f}')",
        "        elif not is_uptrend and is_invested:",
        "            self.Liquidate(self.symbol)",
        "            self.Log(f'SELL {self.symbol}  price={price:.2f}')",
    ]

    # Detect strategy description from docstring if available
    strategy_description = f"Auto-scaffolded strategy for {symbol}."
    strategy_py = os.path.join(code_dir, "strategy.py")
    if os.path.isfile(strategy_py):
        try:
            import ast as _ast
            with open(strategy_py, "r", encoding="utf-8", errors="replace") as fh:
                src = fh.read(2048)
            try:
                tree = _ast.parse(src)
                docstring = _ast.get_docstring(tree)
                if docstring:
                    first_line = docstring.strip().splitlines()[0][:120]
                    strategy_description = first_line
            except SyntaxError:
                pass
        except OSError:
            pass

    content = _LEAN_SCAFFOLD_TEMPLATE.format(
        class_name=class_name,
        strategy_description=strategy_description,
        symbol=symbol,
        indicators="\n".join(indicators_lines),
        trading_logic="\n".join(trading_lines),
    )

    out_dir = os.path.join(run_dir, "code_lean")
    out_path = os.path.join(out_dir, "algorithm.py")
    try:
        os.makedirs(out_dir, exist_ok=True)
        _tmp_out = out_path + ".tmp"
        try:
            with open(_tmp_out, "w", encoding="utf-8") as fh:
                fh.write(content)
            os.replace(_tmp_out, out_path)
        except OSError:
            try:
                os.unlink(_tmp_out)
            except OSError:
                pass
            raise
    except OSError as exc:
        raise RuntimeError(f"generate_lean_scaffold: failed to write {out_path}: {exc}") from exc

    return out_path


# ── Public API ────────────────────────────────────────────────────────────────

def translate_run_to_languages(
    run_dir: str,
    *,
    config: Optional[MultiLangConfig] = None,
    llm: Any,
) -> MultiLangResult:
    """
    Translate all Python files in ``{run_dir}/code/`` to the configured
    target languages.

    Parameters
    ----------
    run_dir:
        Path to a completed pipeline run directory containing ``code/``.
    config:
        ``MultiLangConfig`` specifying target languages and file limits.
        Defaults to TypeScript + Go with env-configured limits.
    llm:
        A LangChain-compatible LLM instance.

    Returns
    -------
    MultiLangResult
        Per-language file lists, individual translation results, and errors.
    """
    if config is None:
        config = MultiLangConfig()

    max_files = config.max_files if config.max_files > 0 else _MAX_FILES
    max_chars = config.max_chars_per_file if config.max_chars_per_file > 0 else _MAX_CHARS

    # Validate requested languages
    invalid = set(config.languages) - _SUPPORTED_TARGETS
    result = MultiLangResult(run_dir=run_dir)
    if invalid:
        result.errors.append(
            f"Unsupported language(s) ignored: {sorted(invalid)}. "
            f"Supported: {sorted(_SUPPORTED_TARGETS)}"
        )
        config = MultiLangConfig(
            languages=[l for l in config.languages if l not in invalid],
            max_files=config.max_files,
            max_chars_per_file=config.max_chars_per_file,
            include_files=config.include_files,
            exclude_files=config.exclude_files,
        )

    if not config.languages:
        result.errors.append(
            "No valid target languages configured. "
            f"Supported: {sorted(_SUPPORTED_TARGETS)}"
        )
        return result

    # Collect source files
    py_files = _collect_python_files(run_dir, config, max_files, max_chars)
    if not py_files:
        result.errors.append(
            f"No Python source files found in {run_dir}/code/ to translate."
        )
        return result

    # Translate each file for each language
    for lang in config.languages:
        result.files_written.setdefault(lang, [])
        for rel_path, source in py_files:
            tr = _translate_file(rel_path, source, lang, run_dir, llm)
            result.translations.append(tr)
            if tr.success:
                result.files_written[lang].append(tr.target_path)
            else:
                result.errors.append(
                    f"[{lang}] {rel_path}: {tr.error}"
                )

    # Write manifest
    manifest_path = os.path.join(run_dir, "multilang_manifest.json")
    try:
        manifest = {
            "run_dir": run_dir,
            "languages": config.languages,
            "source_files": [r for r, _ in py_files],
            "results": {
                lang: result.files_written.get(lang, [])
                for lang in config.languages
            },
            "errors": result.errors,
        }
        _tmp_manifest = manifest_path + ".tmp"
        with open(_tmp_manifest, "w", encoding="utf-8") as fh:
            json.dump(manifest, fh, indent=2, ensure_ascii=False)
        os.replace(_tmp_manifest, manifest_path)
        result.manifest_path = manifest_path
    except OSError:
        try:
            os.unlink(_tmp_manifest)
        except OSError:
            pass

    return result
