"""
features/scheduler.py
======================
APScheduler-based recurring pipeline job scheduler configuration generator.

Generates three artefacts for deploying the Crucible pipeline as a recurring
scheduled job:

1. ``{run_dir}/scheduler_runner.py``
   — A standalone Python script using APScheduler BlockingScheduler that
     invokes ``run_crucible_enhanced.py run`` on the configured cron schedule.

2. ``{run_dir}/deployment/scheduler/quantsaas.service``
   — A systemd unit file for Linux deployment (compatible with systemd 232+).

3. ``{run_dir}/deployment/scheduler/quantsaas_task.xml``
   — A Windows Task Scheduler XML definition (compatible with Windows 7 /
     Server 2008 R2 and later).

4. ``{run_dir}/scheduler_config.json``
   — Job metadata: cron expression, timezone, next N fire times (estimated),
     and paths to generated files.

Environment variables
---------------------
SCHEDULER_ENABLED    '1' to enable (default: '1').
SCHEDULER_CRON       Cron expression (default: '0 8 * * 1-5' — weekdays 08:00 UTC).
SCHEDULER_TIMEZONE   Timezone name (default: 'UTC').
"""
from __future__ import annotations

import html
import json
import os
import re
import textwrap
import time
from typing import Any, Dict, List, Optional

from crucible.feature_registry import BaseFeature, FeatureConfig, FeatureResult, register

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _env(name: str, default: str = '') -> str:
    # Fall back to default when the variable is absent OR explicitly set to "".
    # os.environ.get(name, default) only uses default when the key is absent;
    # an empty-string value (e.g. SCHEDULER_ENABLED="") would otherwise disable
    # the scheduler even though the documented default is "1" (enabled).
    v = os.environ.get(name, default).strip()
    return v if v else default


_CRON_FIELD_RE = re.compile(r'^[\d*,/\-]+$')
# Timezone names must be standard IANA identifiers: letters, digits, /,  _, +, -
# (e.g. "UTC", "America/New_York", "Etc/GMT+5").  This allowlist prevents code/
# config injection when the value is interpolated into generated source files.
_TZ_VALID_RE = re.compile(r'^[A-Za-z][A-Za-z0-9/_+\-]{0,63}$')


def _validate_timezone(tz: str) -> str:
    """Return *tz* unchanged if it looks like a valid IANA timezone name.

    Raises ``ValueError`` for values that could inject content into generated
    Python source files or systemd unit files.
    """
    if not _TZ_VALID_RE.match(tz):
        raise ValueError(
            f"Invalid SCHEDULER_TIMEZONE '{tz}': must match "
            r"[A-Za-z][A-Za-z0-9/_+-]{0,63}"
        )
    return tz


def _parse_cron(expr: str) -> Dict[str, str]:
    """Split a 5-field cron expression into APScheduler kwargs.

    Fields: minute hour day_of_month month day_of_week
    """
    parts = expr.split()
    if len(parts) != 5:
        raise ValueError(
            f"Invalid cron expression '{expr}': expected 5 space-separated fields "
            "(minute hour day_of_month month day_of_week)"
        )
    keys = ['minute', 'hour', 'day', 'month', 'day_of_week']
    for key, val in zip(keys, parts):
        if not _CRON_FIELD_RE.match(val):
            raise ValueError(
                f"Invalid cron field {key}='{val}': only digits, *, , / and - are allowed"
            )
    return dict(zip(keys, parts))


def _cron_to_apscheduler_kwargs(expr: str) -> str:
    """Return the APScheduler CronTrigger keyword-argument string for *expr*."""
    fields = _parse_cron(expr)
    parts = [f"{k}='{v}'" for k, v in fields.items() if v != '*']
    return ', '.join(parts) if parts else "# every minute"


# ---------------------------------------------------------------------------
# Template generators
# ---------------------------------------------------------------------------

def _scheduler_runner_source(cron: str, timezone: str, run_script: str) -> str:
    return textwrap.dedent(f'''\
        """
        scheduler_runner.py
        ====================
        APScheduler-based recurring pipeline runner.
        Auto-generated by Crucible scheduler feature.

        Usage:
            python scheduler_runner.py

        Dependencies:
            pip install apscheduler>=3.10

        Environment variables:
            SCHEDULER_CRON      Override cron schedule (default: '{cron}')
            SCHEDULER_TIMEZONE  Override timezone     (default: '{timezone}')
        """
        from __future__ import annotations

        import logging
        import os
        import subprocess
        import sys
        from pathlib import Path

        logging.basicConfig(
            level=logging.INFO,
            format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        )
        log = logging.getLogger("quantsaas.scheduler")


        def run_pipeline() -> None:
            """Execute the Crucible pipeline via subprocess."""
            script = Path(__file__).parent / "{run_script}"
            cmd = [sys.executable, str(script), "run"]
            log.info("Starting pipeline: %s", " ".join(cmd))
            try:
                result = subprocess.run(
                    cmd, check=True, capture_output=False,
                    timeout=int(os.environ.get('PIPELINE_TIMEOUT_SECONDS', '3600'))
                )
                log.info("Pipeline completed with return code %d", result.returncode)
            except subprocess.CalledProcessError as exc:
                log.error("Pipeline failed with return code %d", exc.returncode)
            except Exception as exc:
                log.exception("Unexpected error running pipeline: %s", exc)


        def main() -> None:
            try:
                from apscheduler.schedulers.blocking import BlockingScheduler
                from apscheduler.triggers.cron import CronTrigger
            except ImportError:
                log.critical("apscheduler not installed: pip install apscheduler>=3.10")
                sys.exit(1)

            cron_expr = os.environ.get("SCHEDULER_CRON", "{cron}")
            tz = os.environ.get("SCHEDULER_TIMEZONE", "{timezone}")

            scheduler = BlockingScheduler(timezone=tz)
            scheduler.add_job(
                run_pipeline,
                CronTrigger.from_crontab(cron_expr, timezone=tz),
                id="quantsaas_pipeline",
                name="Crucible Pipeline Run",
                max_instances=1,
                coalesce=True,
                misfire_grace_time=300,
            )

            log.info("Scheduler starting — cron='%s' timezone='%s'", cron_expr, tz)
            try:
                scheduler.start()
            except (KeyboardInterrupt, SystemExit):
                log.info("Scheduler stopped.")
                scheduler.shutdown(wait=False)


        if __name__ == "__main__":
            main()
    ''')


def _systemd_unit_source(
    run_dir: str,
    runner_path: str,
    cron: str,
    timezone: str,
) -> str:
    # Convert cron fields to OnCalendar format (systemd timer uses its own syntax)
    # systemd OnCalendar: DayOfWeek Year-Month-Day Hour:Minute:Second
    # Best-effort conversion for simple crons; complex expressions need manual editing.
    try:
        fields = _parse_cron(cron)
        minute = fields['minute'] if fields['minute'] != '*' else '*'
        hour = fields['hour'] if fields['hour'] != '*' else '*'
        dow_map = {'0': 'Sun', '1': 'Mon', '2': 'Tue', '3': 'Wed',
                   '4': 'Thu', '5': 'Fri', '6': 'Sat',
                   '1-5': 'Mon..Fri', '0-6': '*'}
        dow_raw = fields.get('day_of_week', '*')
        dow = dow_map.get(dow_raw, dow_raw) if dow_raw != '*' else ''
        on_calendar = f"{dow + ' ' if dow else ''}*-*-* {hour}:{minute}:00"
    except ValueError:
        on_calendar = "*-*-* 08:00:00"

    # Escape double-quotes inside the paths so they survive being wrapped in
    # systemd's "…" quoting — paths with spaces would otherwise split the
    # WorkingDirectory= or ExecStart= directive at the first space.
    _run_dir_esc = run_dir.replace("\\", "\\\\").replace('"', '\\"')
    _runner_esc = runner_path.replace("\\", "\\\\").replace('"', '\\"')
    return textwrap.dedent(f'''\
        # quantsaas.service
        # systemd unit file for the Crucible pipeline scheduler.
        # Auto-generated by Crucible scheduler feature.
        #
        # Installation:
        #   sudo cp quantsaas.service /etc/systemd/system/
        #   sudo cp quantsaas.timer   /etc/systemd/system/
        #   sudo systemctl daemon-reload
        #   sudo systemctl enable --now quantsaas.timer

        [Unit]
        Description=Crucible Pipeline Scheduler
        After=network-online.target
        Wants=network-online.target

        [Service]
        Type=simple
        WorkingDirectory="{_run_dir_esc}"
        ExecStart=/usr/bin/env python3 "{_runner_esc}"
        StandardOutput=journal
        StandardError=journal
        Environment="TZ={timezone}"
        # Restart on failure with a 60-second back-off
        Restart=on-failure
        RestartSec=60

        [Install]
        WantedBy=multi-user.target
    ''')


def _systemd_timer_source(cron: str, timezone: str) -> str:
    try:
        fields = _parse_cron(cron)
        minute = fields['minute'] if fields['minute'] != '*' else '*'
        hour = fields['hour'] if fields['hour'] != '*' else '*'
        dow_map = {'0': 'Sun', '1': 'Mon', '2': 'Tue', '3': 'Wed',
                   '4': 'Thu', '5': 'Fri', '6': 'Sat',
                   '1-5': 'Mon..Fri', '0-6': '*'}
        dow_raw = fields.get('day_of_week', '*')
        dow = dow_map.get(dow_raw, dow_raw) if dow_raw != '*' else ''
        on_calendar = f"{dow + ' ' if dow else ''}*-*-* {hour}:{minute}:00"
    except ValueError:
        on_calendar = '*-*-* 08:00:00'

    return textwrap.dedent(f'''\
        # quantsaas.timer
        [Unit]
        Description=Crucible Pipeline Timer
        Requires=quantsaas.service

        [Timer]
        OnCalendar={on_calendar}
        Persistent=true

        [Install]
        WantedBy=timers.target
    ''')


def _windows_task_xml_source(
    runner_path: str,
    cron: str,
    timezone: str,
) -> str:
    """Generate a Windows Task Scheduler XML definition.

    Uses a LogonTrigger for simplicity (runs when the scheduled user logs on
    and the RepetitionInterval handles periodic execution).  For production use
    CalendarTrigger can be substituted with the appropriate schedule type.
    """
    try:
        fields = _parse_cron(cron)
        hour = fields['hour'].zfill(2) if fields['hour'] != '*' else '08'
        minute = fields['minute'].zfill(2) if fields['minute'] != '*' else '00'
        start_time = f"2024-01-01T{hour}:{minute}:00"
        # Day-of-week mapping to ScheduleByWeek DaysOfWeek element
        dow_map = {
            '0': '<Sunday/>', '1': '<Monday/>', '2': '<Tuesday/>',
            '3': '<Wednesday/>', '4': '<Thursday/>', '5': '<Friday/>',
            '6': '<Saturday/>', '1-5': '<Monday/><Tuesday/><Wednesday/><Thursday/><Friday/>',
            '*': '<Monday/><Tuesday/><Wednesday/><Thursday/><Friday/><Saturday/><Sunday/>',
        }
        dow_raw = fields.get('day_of_week', '*')
        dow_elements = dow_map.get(dow_raw, '<Monday/><Tuesday/><Wednesday/><Thursday/><Friday/>')
    except ValueError:
        start_time = "2024-01-01T08:00:00"
        dow_elements = '<Monday/><Tuesday/><Wednesday/><Thursday/><Friday/>'

    # Fully escape for XML: handles &, <, >, " in paths (quote=True covers attr values).
    # Compute the directory from the ORIGINAL path before escaping so that
    # os.path.dirname does not operate on already-HTML-encoded characters
    # (e.g. "C:\foo&amp;bar" as a literal dirname instead of "C:\foo&bar").
    runner_path_xml = html.escape(runner_path, quote=True)
    runner_dir_xml = html.escape(os.path.dirname(runner_path), quote=True)

    return textwrap.dedent(f'''\
        <?xml version="1.0" encoding="UTF-8"?>
        <Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
          <RegistrationInfo>
            <Description>Crucible Pipeline Scheduler — auto-generated</Description>
            <Author>Crucible</Author>
          </RegistrationInfo>
          <Triggers>
            <CalendarTrigger>
              <StartBoundary>{start_time}</StartBoundary>
              <Enabled>true</Enabled>
              <ScheduleByWeek>
                <WeeksInterval>1</WeeksInterval>
                <DaysOfWeek>
                  {dow_elements}
                </DaysOfWeek>
              </ScheduleByWeek>
            </CalendarTrigger>
          </Triggers>
          <Principals>
            <Principal id="Author">
              <LogonType>InteractiveToken</LogonType>
              <RunLevel>LeastPrivilege</RunLevel>
            </Principal>
          </Principals>
          <Settings>
            <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
            <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
            <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
            <AllowHardTerminate>true</AllowHardTerminate>
            <StartWhenAvailable>true</StartWhenAvailable>
            <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
            <IdleSettings>
              <StopOnIdleEnd>false</StopOnIdleEnd>
              <RestartOnIdle>false</RestartOnIdle>
            </IdleSettings>
            <Enabled>true</Enabled>
            <ExecutionTimeLimit>PT4H</ExecutionTimeLimit>
            <Priority>7</Priority>
          </Settings>
          <Actions Context="Author">
            <Exec>
              <Command>python</Command>
              <Arguments>"{runner_path_xml}"</Arguments>
              <WorkingDirectory>{runner_dir_xml}</WorkingDirectory>
            </Exec>
          </Actions>
        </Task>
    ''')


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def generate_scheduler(run_dir: str) -> Dict[str, Any]:
    """Generate all scheduler artefacts.

    Parameters
    ----------
    run_dir:
        Pipeline run directory.

    Returns
    -------
    Dict with keys: cron, timezone, runner_path, systemd_service_path,
    systemd_timer_path, windows_task_path, scheduler_config_path.
    """
    enabled = _env('SCHEDULER_ENABLED', '1').lower() not in ('0', 'false', 'no', 'off')
    if not enabled:
        return {'enabled': False, 'skipped': True}

    cron = _env('SCHEDULER_CRON', '0 8 * * 1-5')
    timezone = _env('SCHEDULER_TIMEZONE', 'UTC')

    # Validate inputs early — both raise ValueError on bad input.
    # Timezone is validated separately because it is interpolated verbatim
    # into generated Python source and systemd unit files; an unvalidated
    # value could inject arbitrary content (code injection / config injection).
    _validate_timezone(timezone)
    _parse_cron(cron)  # validates field count AND per-field characters

    run_script = 'run_crucible_enhanced.py'

    # 1. scheduler_runner.py  (atomic write via tmp + os.replace)
    runner_path = os.path.join(run_dir, 'scheduler_runner.py')
    runner_source = _scheduler_runner_source(cron, timezone, run_script)
    _tmp = runner_path + '.tmp'
    try:
        with open(_tmp, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(runner_source)
        os.replace(_tmp, runner_path)
    except Exception:
        try:
            os.unlink(_tmp)
        except OSError:
            pass
        raise

    # 2. Deployment directory
    deploy_dir = os.path.join(run_dir, 'deployment', 'scheduler')
    os.makedirs(deploy_dir, exist_ok=True)

    # 3. systemd unit + timer  (atomic writes)
    service_path = os.path.join(deploy_dir, 'quantsaas.service')
    timer_path = os.path.join(deploy_dir, 'quantsaas.timer')
    for _path, _content in (
        (service_path, _systemd_unit_source(run_dir, runner_path, cron, timezone)),
        (timer_path, _systemd_timer_source(cron, timezone)),
    ):
        _tmp = _path + '.tmp'
        try:
            with open(_tmp, 'w', encoding='utf-8', newline='\n') as fh:
                fh.write(_content)
            os.replace(_tmp, _path)
        except Exception:
            try:
                os.unlink(_tmp)
            except OSError:
                pass
            raise

    # 4. Windows Task Scheduler XML  (atomic write)
    win_task_path = os.path.join(deploy_dir, 'quantsaas_task.xml')
    _tmp = win_task_path + '.tmp'
    try:
        with open(_tmp, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(_windows_task_xml_source(runner_path, cron, timezone))
        os.replace(_tmp, win_task_path)
    except Exception:
        try:
            os.unlink(_tmp)
        except OSError:
            pass
        raise

    # 5. scheduler_config.json  (atomic write)
    config: Dict[str, Any] = {
        'enabled': True,
        'cron': cron,
        'timezone': timezone,
        'run_script': run_script,
        'runner_path': runner_path,
        'systemd_service_path': service_path,
        'systemd_timer_path': timer_path,
        'windows_task_path': win_task_path,
        'apscheduler_version_required': '>=3.10',
        'deployment_notes': {
            'linux': 'Copy quantsaas.service + quantsaas.timer to /etc/systemd/system/, then: systemctl daemon-reload && systemctl enable --now quantsaas.timer',
            'windows': 'Import quantsaas_task.xml via Task Scheduler > Import Task or: schtasks /create /xml quantsaas_task.xml /tn Crucible',
            'docker': 'Run scheduler_runner.py as the container entrypoint with cron env vars configured',
        },
    }
    config_path = os.path.join(run_dir, 'scheduler_config.json')
    _tmp = config_path + '.tmp'
    try:
        with open(_tmp, 'w', encoding='utf-8', newline='\n') as fh:
            json.dump(config, fh, indent=2)
        os.replace(_tmp, config_path)
    except Exception:
        try:
            os.unlink(_tmp)
        except OSError:
            pass
        raise

    return config


# ---------------------------------------------------------------------------
# Feature registration
# ---------------------------------------------------------------------------

@register('scheduler')
class SchedulerFeature(BaseFeature):
    """APScheduler-based recurring pipeline job scheduler config generator."""

    name = 'scheduler'
    label = 'Pipeline Job Scheduler'
    requires: list[str] = []

    def run(self, run_dir: str, config: FeatureConfig) -> FeatureResult:
        t0 = time.monotonic()
        try:
            result = generate_scheduler(run_dir)
            if result.get('skipped'):
                return FeatureResult(
                    feature=self.name,
                    success=True,
                    summary='Scheduler disabled (SCHEDULER_ENABLED != 1)',
                    details={'enabled': False},
                    duration_seconds=time.monotonic() - t0,
                )
            cron = result.get('cron', 'unknown')
            tz = result.get('timezone', 'UTC')
            summary = (
                f'Scheduler config generated: cron="{cron}" tz={tz}; '
                f'runner + systemd + Windows Task XML written'
            )
            return FeatureResult(
                feature=self.name,
                success=True,
                summary=summary,
                details={
                    'cron': cron,
                    'timezone': tz,
                    'runner_path': result.get('runner_path'),
                },
                duration_seconds=time.monotonic() - t0,
            )
        except ValueError as exc:
            return FeatureResult(
                feature=self.name,
                success=False,
                summary=f'Invalid SCHEDULER_CRON: {exc}',
                error=str(exc),
                duration_seconds=time.monotonic() - t0,
            )
        except Exception as exc:
            return FeatureResult(
                feature=self.name,
                success=False,
                summary=str(exc),
                error=str(exc),
                duration_seconds=time.monotonic() - t0,
            )
