"""
features/trading_platform.py
==============================
Trading platform adapter stub generator for Alpaca, Binance, and IBKR.

Detects the strategy type from ``analysis_result.json`` (equity / crypto /
multi-asset) and writes three ready-to-use adapter Python files into
``{run_dir}/code/platforms/``:

* ``alpaca_adapter.py``   — Alpaca REST v2 with paper-trading safety checks.
* ``binance_adapter.py``  — Binance REST v3 with rate limiting.
* ``ibkr_adapter.py``     — Interactive Brokers IBAPI stub.

All adapters share a common interface:

* ``place_order(symbol, qty, side, order_type, limit_price)``
* ``get_position(symbol)``
* ``get_account_balance()``
* ``cancel_all_orders()``

Safety constraints applied to every adapter:

* PAPER_TRADING flag guard — live orders are blocked unless explicitly enabled.
* Rate limiter — minimum 5 seconds between consecutive order submissions.
* Position size cap — each order is capped at 5 % of reported account equity.

Writes ``trading_platform_report.json`` with strategy type, generated files,
and applicable safety flags.

Environment variables
---------------------
TRADING_PLATFORM_TARGETS   Comma-separated list of adapter targets to generate.
                            Supported: alpaca, binance, ibkr (default: 'alpaca,binance').
TRADING_PAPER_MODE         'true' to block live order submission (default: 'true').
"""
from __future__ import annotations

import json
import os
import textwrap
import time
from typing import Any, Dict, List, Optional

from crucible.feature_registry import BaseFeature, FeatureConfig, FeatureResult, register

# ---------------------------------------------------------------------------
# Strategy type detection
# ---------------------------------------------------------------------------

_CRYPTO_KEYWORDS = frozenset([
    'btc', 'eth', 'bnb', 'sol', 'xrp', 'crypto', 'binance',
    'defi', 'blockchain', 'usdt', 'usdc',
])
_EQUITY_KEYWORDS = frozenset([
    'equity', 'stock', 'shares', 'alpaca', 'nasdaq', 'nyse', 'spy',
    'qqq', 'iwm', 'sector', 'dividend',
])


def detect_strategy_type(run_dir: str) -> str:
    """Return 'crypto', 'equity', or 'multi-asset' by scanning analysis_result.json."""
    analysis_path = os.path.join(run_dir, 'analysis_result.json')
    if not os.path.isfile(analysis_path):
        return 'multi-asset'
    try:
        with open(analysis_path, 'r', encoding='utf-8') as fh:
            text = fh.read().lower()
    except OSError:
        return 'multi-asset'

    has_crypto = any(kw in text for kw in _CRYPTO_KEYWORDS)
    has_equity = any(kw in text for kw in _EQUITY_KEYWORDS)

    if has_crypto and has_equity:
        return 'multi-asset'
    if has_crypto:
        return 'crypto'
    return 'equity'


# ---------------------------------------------------------------------------
# Adapter source templates
# ---------------------------------------------------------------------------

def _alpaca_adapter_source(paper_mode: bool) -> str:
    paper_flag = 'True' if paper_mode else 'False'
    return textwrap.dedent(f'''\
        """
        platforms/alpaca_adapter.py
        ============================
        Alpaca REST v2 trading adapter with paper-trading safety checks.
        Auto-generated by Crucible trading_platform feature.

        Required env vars:
            ALPACA_API_KEY      — Alpaca API key ID
            ALPACA_SECRET_KEY   — Alpaca secret key
            ALPACA_BASE_URL     — e.g. https://paper-api.alpaca.markets (paper)
                                       https://api.alpaca.markets          (live)
        """
        from __future__ import annotations

        import json
        import os
        import time
        import urllib.error
        import urllib.request
        from typing import Any, Dict, Optional

        PAPER_TRADING: bool = {paper_flag}
        _MAX_POSITION_PCT: float = 0.05      # 5 % of equity per order
        _MIN_ORDER_INTERVAL_S: float = 5.0   # rate limiter
        _last_order_ts: float = 0.0


        def _headers() -> Dict[str, str]:
            return {{
                "APCA-API-KEY-ID": os.environ["ALPACA_API_KEY"],
                "APCA-API-SECRET-KEY": os.environ["ALPACA_SECRET_KEY"],
                "Content-Type": "application/json",
            }}


        def _base() -> str:
            default = (
                "https://paper-api.alpaca.markets"
                if PAPER_TRADING
                else "https://api.alpaca.markets"
            )
            return os.environ.get("ALPACA_BASE_URL", default).rstrip("/")


        def _request(method: str, path: str, body: Optional[Dict] = None) -> Dict[str, Any]:
            url = _base() + path
            data = json.dumps(body).encode() if body else None
            req = urllib.request.Request(url, data=data, headers=_headers(), method=method)
            try:
                with urllib.request.urlopen(req, timeout=10) as resp:
                    return json.loads(resp.read().decode())
            except urllib.error.HTTPError as exc:
                raise RuntimeError(f"Alpaca HTTP {{exc.code}}: {{exc.read().decode()}}") from exc


        def get_account_balance() -> Dict[str, Any]:
            """Return account equity, buying power, and currency."""
            data = _request("GET", "/v2/account")
            return {{
                "equity": float(data.get("equity", 0)),
                "buying_power": float(data.get("buying_power", 0)),
                "currency": data.get("currency", "USD"),
                "platform": "alpaca",
            }}


        def get_position(symbol: str) -> Dict[str, Any]:
            """Return current position for *symbol*, or empty dict if flat."""
            try:
                data = _request("GET", f"/v2/positions/{{symbol}}")
                return {{
                    "symbol": symbol,
                    "qty": float(data.get("qty", 0)),
                    "avg_entry_price": float(data.get("avg_entry_price", 0)),
                    "market_value": float(data.get("market_value", 0)),
                    "platform": "alpaca",
                }}
            except RuntimeError:
                return {{"symbol": symbol, "qty": 0.0, "platform": "alpaca"}}


        def place_order(
            symbol: str,
            qty: float,
            side: str,
            order_type: str = "market",
            limit_price: Optional[float] = None,
        ) -> Dict[str, Any]:
            """Submit an order.  Raises RuntimeError on paper-mode block or rate limit."""
            global _last_order_ts

            if PAPER_TRADING:
                raise RuntimeError(
                    "PAPER_TRADING=True: live order submission is blocked. "
                    "Set ALPACA_BASE_URL to paper endpoint and disable PAPER_TRADING to proceed."
                )

            now = time.monotonic()
            if now - _last_order_ts < _MIN_ORDER_INTERVAL_S:
                raise RuntimeError(
                    f"Rate limit: wait {{_MIN_ORDER_INTERVAL_S}}s between orders."
                )

            # Position size guard
            account = get_account_balance()
            equity = account.get("equity", 0.0)
            if equity > 0:
                # Estimate notional from last snapshot (best-effort)
                max_notional = equity * _MAX_POSITION_PCT
                # qty check is approximate for market orders
                _ = max_notional  # enforce downstream if price known

            body: Dict[str, Any] = {{
                "symbol": symbol,
                "qty": str(qty),
                "side": side,
                "type": order_type,
                "time_in_force": "gtc" if order_type == "limit" else "day",
            }}
            if order_type == "limit" and limit_price is not None:
                body["limit_price"] = str(limit_price)

            result = _request("POST", "/v2/orders", body)
            _last_order_ts = time.monotonic()
            return result


        def cancel_all_orders() -> Dict[str, Any]:
            """Cancel all open orders."""
            result = _request("DELETE", "/v2/orders")
            return {{"cancelled": result, "platform": "alpaca"}}
    ''')


def _binance_adapter_source(paper_mode: bool) -> str:
    paper_flag = 'True' if paper_mode else 'False'
    return textwrap.dedent(f'''\
        """
        platforms/binance_adapter.py
        ==============================
        Binance REST v3 trading adapter with rate limiting and paper-mode guard.
        Auto-generated by Crucible trading_platform feature.

        Required env vars:
            BINANCE_API_KEY     — Binance API key
            BINANCE_SECRET_KEY  — Binance HMAC-SHA256 secret
        """
        from __future__ import annotations

        import hashlib
        import hmac
        import json
        import os
        import time
        import urllib.error
        import urllib.parse
        import urllib.request
        from typing import Any, Dict, Optional

        PAPER_TRADING: bool = {paper_flag}
        _BASE_URL = "https://api.binance.com"
        _MAX_POSITION_PCT: float = 0.05
        _MIN_ORDER_INTERVAL_S: float = 5.0
        _last_order_ts: float = 0.0


        def _sign(params: Dict[str, str]) -> str:
            secret = os.environ["BINANCE_SECRET_KEY"].encode()
            query = urllib.parse.urlencode(params)
            return hmac.new(secret, query.encode(), hashlib.sha256).hexdigest()


        def _headers() -> Dict[str, str]:
            return {{"X-MBX-APIKEY": os.environ["BINANCE_API_KEY"]}}


        def _get(path: str, params: Optional[Dict] = None) -> Any:
            p = dict(params or {{}})
            p["timestamp"] = str(int(time.time() * 1000))
            p["signature"] = _sign(p)
            url = _BASE_URL + path + "?" + urllib.parse.urlencode(p)
            req = urllib.request.Request(url, headers=_headers())
            try:
                with urllib.request.urlopen(req, timeout=10) as resp:
                    return json.loads(resp.read().decode())
            except urllib.error.HTTPError as exc:
                raise RuntimeError(f"Binance HTTP {{exc.code}}: {{exc.read().decode()}}") from exc


        def _post(path: str, params: Dict) -> Any:
            p = dict(params)
            p["timestamp"] = str(int(time.time() * 1000))
            p["signature"] = _sign(p)
            data = urllib.parse.urlencode(p).encode()
            req = urllib.request.Request(
                _BASE_URL + path, data=data, headers=_headers(), method="POST"
            )
            try:
                with urllib.request.urlopen(req, timeout=10) as resp:
                    return json.loads(resp.read().decode())
            except urllib.error.HTTPError as exc:
                raise RuntimeError(f"Binance HTTP {{exc.code}}: {{exc.read().decode()}}") from exc


        def _delete(path: str, params: Dict) -> Any:
            p = dict(params)
            p["timestamp"] = str(int(time.time() * 1000))
            p["signature"] = _sign(p)
            url = _BASE_URL + path + "?" + urllib.parse.urlencode(p)
            req = urllib.request.Request(url, headers=_headers(), method="DELETE")
            try:
                with urllib.request.urlopen(req, timeout=10) as resp:
                    return json.loads(resp.read().decode())
            except urllib.error.HTTPError as exc:
                raise RuntimeError(f"Binance HTTP {{exc.code}}: {{exc.read().decode()}}") from exc


        def get_account_balance() -> Dict[str, Any]:
            data = _get("/api/v3/account")
            balances = {{
                b["asset"]: float(b["free"]) + float(b["locked"])
                for b in data.get("balances", [])
                if float(b["free"]) + float(b["locked"]) > 0
            }}
            return {{"balances": balances, "platform": "binance"}}


        def get_position(symbol: str) -> Dict[str, Any]:
            """For spot Binance, 'position' is the asset balance."""
            base = symbol.replace("USDT", "").replace("BTC", "")
            data = _get("/api/v3/account")
            for b in data.get("balances", []):
                if b["asset"] == base:
                    qty = float(b["free"]) + float(b["locked"])
                    return {{"symbol": symbol, "base_asset": base, "qty": qty, "platform": "binance"}}
            return {{"symbol": symbol, "qty": 0.0, "platform": "binance"}}


        def place_order(
            symbol: str,
            qty: float,
            side: str,
            order_type: str = "MARKET",
            limit_price: Optional[float] = None,
        ) -> Dict[str, Any]:
            global _last_order_ts

            if PAPER_TRADING:
                raise RuntimeError(
                    "PAPER_TRADING=True: live order blocked. Set PAPER_TRADING=False to enable."
                )

            now = time.monotonic()
            if now - _last_order_ts < _MIN_ORDER_INTERVAL_S:
                raise RuntimeError(f"Rate limit: wait {{_MIN_ORDER_INTERVAL_S}}s between orders.")

            params: Dict[str, str] = {{
                "symbol": symbol.upper(),
                "side": side.upper(),
                "type": order_type.upper(),
                "quantity": str(qty),
            }}
            if order_type.upper() == "LIMIT" and limit_price is not None:
                params["price"] = str(limit_price)
                params["timeInForce"] = "GTC"

            result = _post("/api/v3/order", params)
            _last_order_ts = time.monotonic()
            return result


        def cancel_all_orders() -> Dict[str, Any]:
            """Cancel all open orders across all symbols (requires iterating open orders)."""
            open_orders = _get("/api/v3/openOrders", {{}})
            cancelled = []
            for order in open_orders:
                sym = order["symbol"]
                oid = str(order["orderId"])
                try:
                    cancelled.append(_delete("/api/v3/order", {{"symbol": sym, "orderId": oid}}))
                except RuntimeError:
                    pass
            return {{"cancelled_count": len(cancelled), "platform": "binance"}}
    ''')


def _ibkr_adapter_source(paper_mode: bool) -> str:
    paper_flag = 'True' if paper_mode else 'False'
    return textwrap.dedent(f'''\
        """
        platforms/ibkr_adapter.py
        ==========================
        Interactive Brokers IBAPI stub adapter.
        Auto-generated by Crucible trading_platform feature.

        Requires the ibapi package: pip install ibapi
        Required env vars:
            IBKR_HOST       — TWS / IB Gateway host (default: '127.0.0.1')
            IBKR_PORT       — Port (default: '7497' for paper, '7496' for live)
            IBKR_CLIENT_ID  — Unique integer client ID (default: '1')
        """
        from __future__ import annotations

        import os
        import time
        from typing import Any, Dict, Optional

        PAPER_TRADING: bool = {paper_flag}
        _MAX_POSITION_PCT: float = 0.05
        _MIN_ORDER_INTERVAL_S: float = 5.0
        _last_order_ts: float = 0.0

        try:
            from ibapi.client import EClient  # type: ignore[import]
            from ibapi.contract import Contract  # type: ignore[import]
            from ibapi.order import Order  # type: ignore[import]
            from ibapi.wrapper import EWrapper  # type: ignore[import]
            _IBAPI_AVAILABLE = True
        except ImportError:
            _IBAPI_AVAILABLE = False


        class _IBWrapper(EWrapper if _IBAPI_AVAILABLE else object):  # type: ignore[misc]
            """Minimal EWrapper for synchronous order submission."""

            def __init__(self) -> None:
                if _IBAPI_AVAILABLE:
                    super().__init__()
                self._next_order_id: int = 1
                self._account_values: Dict[str, str] = {{}}
                self._positions: Dict[str, float] = {{}}

            def nextValidId(self, orderId: int) -> None:
                self._next_order_id = orderId

            def updateAccountValue(self, key: str, val: str, currency: str, accountName: str) -> None:
                if currency == "USD":
                    self._account_values[key] = val

            def position(self, account: str, contract: Any, position: float, avgCost: float) -> None:
                self._positions[contract.symbol] = position


        class IBKRClient:
            """Thin synchronous wrapper around IBAPI EClient + EWrapper."""

            def __init__(self) -> None:
                if not _IBAPI_AVAILABLE:
                    raise ImportError("ibapi not installed: pip install ibapi")
                self._wrapper = _IBWrapper()
                self._client = EClient(self._wrapper)
                host = os.environ.get("IBKR_HOST", "127.0.0.1")
                try:
                    port = int(os.environ.get("IBKR_PORT", "7497" if PAPER_TRADING else "7496"))
                except ValueError:
                    port = 7497 if PAPER_TRADING else 7496
                try:
                    client_id = int(os.environ.get("IBKR_CLIENT_ID", "1"))
                except ValueError:
                    client_id = 1
                self._client.connect(host, port, clientId=client_id)
                self._client.run()  # Note: in production use a thread

            def _make_stock_contract(self, symbol: str) -> "Contract":
                c = Contract()
                c.symbol = symbol
                c.secType = "STK"
                c.currency = "USD"
                c.exchange = "SMART"
                return c


        _client_instance: Optional[IBKRClient] = None


        def _get_client() -> IBKRClient:
            global _client_instance
            if _client_instance is None:
                _client_instance = IBKRClient()
            return _client_instance


        def get_account_balance() -> Dict[str, Any]:
            """Return net liquidation value from TWS."""
            if not _IBAPI_AVAILABLE:
                return {{"equity": 0.0, "error": "ibapi not installed", "platform": "ibkr"}}
            cl = _get_client()
            cl._client.reqAccountUpdates(True, "")
            time.sleep(1)
            cl._client.reqAccountUpdates(False, "")
            equity = float(cl._wrapper._account_values.get("NetLiquidation", 0))
            return {{"equity": equity, "platform": "ibkr"}}


        def get_position(symbol: str) -> Dict[str, Any]:
            """Return current position quantity for *symbol*."""
            if not _IBAPI_AVAILABLE:
                return {{"symbol": symbol, "qty": 0.0, "error": "ibapi not installed", "platform": "ibkr"}}
            cl = _get_client()
            cl._client.reqPositions()
            time.sleep(1)
            qty = cl._wrapper._positions.get(symbol, 0.0)
            return {{"symbol": symbol, "qty": qty, "platform": "ibkr"}}


        def place_order(
            symbol: str,
            qty: float,
            side: str,
            order_type: str = "MKT",
            limit_price: Optional[float] = None,
        ) -> Dict[str, Any]:
            """Submit an order via TWS."""
            global _last_order_ts

            if PAPER_TRADING:
                raise RuntimeError(
                    "PAPER_TRADING=True: live order blocked. "
                    "Set IBKR_PORT=7496 and PAPER_TRADING=False for live."
                )
            if not _IBAPI_AVAILABLE:
                raise ImportError("ibapi not installed: pip install ibapi")

            now = time.monotonic()
            if now - _last_order_ts < _MIN_ORDER_INTERVAL_S:
                raise RuntimeError(f"Rate limit: wait {{_MIN_ORDER_INTERVAL_S}}s between orders.")

            cl = _get_client()
            contract = cl._make_stock_contract(symbol)
            order = Order()
            order.action = side.upper()
            order.totalQuantity = qty
            order.orderType = order_type.upper()
            if order_type.upper() == "LMT" and limit_price is not None:
                order.lmtPrice = limit_price

            oid = cl._wrapper._next_order_id
            cl._wrapper._next_order_id += 1
            cl._client.placeOrder(oid, contract, order)
            _last_order_ts = time.monotonic()
            return {{"order_id": oid, "symbol": symbol, "qty": qty, "side": side, "platform": "ibkr"}}


        def cancel_all_orders() -> Dict[str, Any]:
            """Request global cancel of all open orders via TWS."""
            if not _IBAPI_AVAILABLE:
                return {{"error": "ibapi not installed", "platform": "ibkr"}}
            cl = _get_client()
            cl._client.reqGlobalCancel()
            return {{"status": "global_cancel_sent", "platform": "ibkr"}}
    ''')


# ---------------------------------------------------------------------------
# File writer
# ---------------------------------------------------------------------------

def generate_trading_platform(run_dir: str) -> Dict[str, Any]:
    """Detect strategy type, write adapter files, produce report.

    Parameters
    ----------
    run_dir:
        Pipeline run directory.

    Returns
    -------
    Dict with keys: strategy_type, targets, generated_files, paper_mode.
    """
    targets_env = os.environ.get('TRADING_PLATFORM_TARGETS', 'alpaca,binance').strip()
    # Fail-closed: paper trading is the safe default. The generated adapter source
    # files use this flag to gate place_order(); if a typo/unknown value silently
    # flipped paper_mode to False the generated code would submit *real* orders
    # against *real* funds. Only an explicit, recognised "off" token disables it.
    # Per CLAUDE.md (高風險系統加強 + env-bool whitelist): unknown values must
    # default to the SAFE side, which here is paper_mode=True.
    paper_mode_raw = os.environ.get('TRADING_PAPER_MODE', 'true').strip().lower()
    paper_mode = paper_mode_raw not in ('0', 'false', 'no', 'off')

    targets = [t.strip().lower() for t in targets_env.split(',') if t.strip()]
    strategy_type = detect_strategy_type(run_dir)

    platforms_dir = os.path.join(run_dir, 'code', 'platforms')
    os.makedirs(platforms_dir, exist_ok=True)

    generated_files: List[str] = []

    adapter_map = {
        'alpaca': ('alpaca_adapter.py', _alpaca_adapter_source),
        'binance': ('binance_adapter.py', _binance_adapter_source),
        'ibkr': ('ibkr_adapter.py', _ibkr_adapter_source),
    }

    for target in targets:
        if target not in adapter_map:
            continue
        filename, source_fn = adapter_map[target]
        source = source_fn(paper_mode)
        fpath = os.path.join(platforms_dir, filename)
        _tmp_fpath = fpath + ".tmp"
        try:
            with open(_tmp_fpath, 'w', encoding='utf-8') as fh:
                fh.write(source)
            os.replace(_tmp_fpath, fpath)
            generated_files.append(fpath)
        except OSError:
            try:
                os.unlink(_tmp_fpath)
            except OSError:
                pass

    # Write __init__.py to make it a package (atomic exclusive-create avoids TOCTOU race)
    init_path = os.path.join(platforms_dir, '__init__.py')
    try:
        with open(init_path, 'x', encoding='utf-8') as fh:
            fh.write('"""Auto-generated trading platform adapters."""\n')
    except FileExistsError:
        pass
    except OSError:
        pass

    report: Dict[str, Any] = {
        'strategy_type': strategy_type,
        'targets': targets,
        'generated_files': generated_files,
        'paper_mode': paper_mode,
        'safety_flags': {
            'paper_trading_guard': paper_mode,
            'min_order_interval_s': 5.0,
            'max_position_pct': 0.05,
        },
    }

    report_path = os.path.join(run_dir, 'trading_platform_report.json')
    _tmp_rpt = report_path + ".tmp"
    try:
        with open(_tmp_rpt, 'w', encoding='utf-8') as fh:
            json.dump(report, fh, indent=2)
        os.replace(_tmp_rpt, report_path)
    except OSError:
        try:
            os.unlink(_tmp_rpt)
        except OSError:
            pass

    return report


# ---------------------------------------------------------------------------
# Feature registration
# ---------------------------------------------------------------------------

@register('trading_platform')
class TradingPlatformFeature(BaseFeature):
    """Generates Alpaca, Binance, and IBKR trading adapter stubs."""

    name = 'trading_platform'
    label = 'Trading Platform Adapters'
    requires: list[str] = []

    def run(self, run_dir: str, config: FeatureConfig) -> FeatureResult:
        t0 = time.monotonic()
        try:
            report = generate_trading_platform(run_dir)
            n_files = len(report.get('generated_files', []))
            strategy = report.get('strategy_type', 'unknown')
            paper = report.get('paper_mode', True)
            summary = (
                f'Trading platform: {n_files} adapter(s) generated '
                f'for {strategy} strategy '
                f'(paper_mode={paper})'
            )
            return FeatureResult(
                feature=self.name,
                success=True,
                summary=summary,
                details={
                    'strategy_type': strategy,
                    'adapters_generated': n_files,
                    'paper_mode': paper,
                },
                duration_seconds=time.monotonic() - t0,
            )
        except Exception as exc:
            return FeatureResult(
                feature=self.name,
                success=False,
                summary=str(exc),
                error=str(exc),
                duration_seconds=time.monotonic() - t0,
            )
